name: Run Calculator Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: installs dependencies
        run: npm install 
      - name: runs build
        run: npm run build
      - name: runs test
        run: npm run test   
