name: Run Calculator Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  commit:
      branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: installs dependencies
        run: npm install 
      - name: runs build
        run: npm run build
      - name: runs test
        run: npm run test   
      - name: running on every commit 
        run:    